cng: fix: add new policies pages path
undistro/undistro.io pull request #73
Opened 2022-11-02 18:39 UTC by raphaelmelo

## Description
Please include a summary of the change, the motivation, and any additional context that helps others understand your PR.

## Linked Issues
If these changes close one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

2022-11-02 18:51 UTC, carlostrr approved these changes

2022-11-02 19:06 UTC, monuelo requested changes
It would help if you didn't point to these paths, leading to a page with a different language.

Consider using Docusaurus [`<Link>`](https://docusaurus.io/docs/docusaurus-core#link) Component instead, or apply the suggestions I've made.

2022-11-02 19:06 UTC, monuelo commented on src/pages/termos-de-uso.js
> +              <a href="/privacy-policy">Política de Privacidade</a>
This ref shouldn't point to the English version of this page.
```suggestion
              <a href="/pt/privacy-policy">Política de Privacidade</a>
```

2022-11-02 19:06 UTC, monuelo commented on src/pages/termos-de-uso.js
> +              <a href="/cookie-policy">Política de Cookies</a>
This ref shouldn't point to the English version of this page.
```suggestion
              <a href="/pt/cookie-policy">Política de Cookies</a>
```

2022-11-02 19:21 UTC, raphaelmelo commented
> Done!

2022-11-03 14:00 UTC, monuelo approved these changes

2022-11-03 14:00 UTC, merged